"""Public API for GRAPE coefficient workflows using microseconds and megahertz."""
from .baselines import (
    BasisSpec,
    GrapeBaselineConfig,
    PulseShapeSpec,
    TimeGridSpec,
    build_grape_baseline,
    write_baseline,
)
from .config import BaselineSpec, ExperimentConfig, PenaltyConfig, override_from_dict
from .result import Result
from .workflows import available_optimizers, register_optimizer, run_experiment
from .physics import (
    make_time_grid,
    hamiltonian_t,
    propagate_piecewise_const,
    propagate_with_controls,
    bloch_components,
    fidelity_pure,
    adjoint_steps,
    rho_to_state,
)
from .cost import (
    terminal_infidelity,
    total_cost,
    grad_terminal_wrt_controls,
    accumulate_cost_and_grads,
)
from .penalties import compute_penalties, penalty_terms
from .controls import (
    crab_linear_basis,
    coeffs_to_control,
    grad_control_wrt_coeffs,
    ensure_time_grid_match,
    normalize_basis_columns,
    harmonic_sine_basis,
    build_normalized_harmonic_bases,
)
from .plotting import (
    plot_cost_history,
    plot_pulses,
    plot_summary,
    plot_penalties_history,
    plot_robustness_heatmap,
    save_figure,
)
from .utils import ensure_dir, json_ready, require_real_finite, set_random_seed, time_block
from .notebook_runners import (
    BaselineArrays,
    prepare_baseline,
    coerce_vector,
    build_base_config,
    method_options,
)
from .analysis import (
    HistorySeries,
    PulseSummary,
    ResultSummary,
    TrajectoryBundle,
    TrajectoryRequest,
    collect_history_series,
    compute_bloch_bundle,
    compute_population_trace,
    compute_trajectory_bundle,
    load_result_summary,
    plot_cost_components,
    plot_cost_histories,
    plot_population_traces,
    plot_pulse_overlay,
    plot_runtime_oracle_bars,
    render_step_size_dashboard,
    render_summary_table,
    summarize_result,
)
__all__ = [
    "BaselineSpec",
    "BasisSpec",
    "ExperimentConfig",
    "GrapeBaselineConfig",
    "PenaltyConfig",
    "PulseShapeSpec",
    "TimeGridSpec",
    "accumulate_cost_and_grads",
    "adjoint_steps",
    "available_optimizers",
    "bloch_components",
    "build_grape_baseline",
    "coeffs_to_control",
    "compute_penalties",
    "crab_linear_basis",
    "harmonic_sine_basis",
    "ensure_dir",
    "ensure_time_grid_match",
    "fidelity_pure",
    "grad_control_wrt_coeffs",
    "grad_terminal_wrt_controls",
    "build_normalized_harmonic_bases",
    "hamiltonian_t",
    "json_ready",
    "make_time_grid",
    "normalize_basis_columns",
    "override_from_dict",
    "penalty_terms",
    "plot_cost_history",
    "plot_penalties_history",
    "plot_pulses",
    "plot_robustness_heatmap",
    "plot_summary",
    "save_figure",
    "propagate_piecewise_const",
    "propagate_with_controls",
    "register_optimizer",
    "rho_to_state",
    "require_real_finite",
    "Result",
    "run_experiment",
    "set_random_seed",
    "terminal_infidelity",
    "time_block",
    "total_cost",
    "write_baseline",
    "BaselineArrays",
    "build_base_config",
    "coerce_vector",
    "method_options",
    "prepare_baseline",
    "HistorySeries",
    "PulseSummary",
    "ResultSummary",
    "TrajectoryBundle",
    "TrajectoryRequest",
    "collect_history_series",
    "compute_bloch_bundle",
    "compute_population_trace",
    "compute_trajectory_bundle",
    "load_result_summary",
    "plot_cost_components",
    "plot_cost_histories",
    "plot_population_traces",
    "plot_pulse_overlay",
    "plot_runtime_oracle_bars",
    "render_step_size_dashboard",
    "render_summary_table",
    "summarize_result",
]
